### ISSUE TITLE
希望追加总经验值排序与点击栏位排序的功能

### ISSUE THREAD

**Issue by Jasonnor** [poooi/plugin-ship-info#26]
1. 总经验值排序，现有是以等级来排序，同等级就会用名字来排，不过常常会需要看同等内经验值最少的舰娘，强烈希望追加
2. 点击栏位排序的功能，就像KCV或舰これ统计データベース那样的表格，比较方便筛选

**Comment by yukixz** [comment]
「等级排序」功能的排序规则是与游戏内「等级排序」的规则相同的。
即：插件内按等级排序时，舰娘顺序与游戏内完全相同。

**Comment by Jasonnor** [comment]
是的，这个我了解
只是不知道有没有办法取到「距离升等剩馀经验」的数据，然後同等内以此来排序？真心期望有这个筛选项
