### ISSUE TITLE
Add the fleet id that a ship currently belongs to

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-ship-info#31]
![image](https://cloud.githubusercontent.com/assets/1596656/10867553/58d56e3e-8036-11e5-97a0-b327e1de5c5f.png)
这个东西。
在安排远征队的时候很有用QwQ
【不过这样就需要多监听一个端口了？

**Comment by KochiyaOcean** [comment]
不是有筛选远征的项目了么

**Comment by dkwingsmt** [comment]
晚上睡觉之前一次安排三个远征队……还没发出去的时候。
确实我现在就是不得不发一个然后看下一队……

**Comment by Ayaphis** [comment]
唔这个显示在哪里好呢，现在宽度都不太够啊=。=

**Comment by KochiyaOcean** [comment]
新窗口插件直接加大窗口宽度不就行了

**Comment by yukixz** [comment]
现在舰娘信息的窗口好宽啊=。=

**Comment by KagamiChan** [comment]
impl. via 10560d9c2c523958b84a340bb8354d68759fc776
