### ISSUE TITLE
显示bug

### ISSUE THREAD

**Issue by jackarcher** [poooi/plugin-ship-info#32]
![261c tmp](https://cloud.githubusercontent.com/assets/6699600/10977387/dbe23002-8444-11e5-939f-7e50c635ebf3.jpg)
希望添加:
一键排序显示所有要修理船(类似航海日志那个)
舰娘经验值

**Comment by KochiyaOcean** [comment]
只能显示总入渠时间，不能随修理时间更新
入渠时间已经是排序项目了

**Comment by Ayaphis** [comment]
这是要把已入渠的船的修理时间标记为0是吧

**Comment by jackarcher** [comment]
额 昨天晚上太晚没写清楚, 新功能是下面写的希望添加里的内容,
bug为:25/50应为中破 染色标记为小破

**Comment by Ayaphis** [comment]
这样。。。

**Comment by jackarcher** [comment]
辛苦各位dalao Orz

**Comment by jackarcher** [comment]
if nowhp < 0.25 * maxhp
      repairColor = 'rgba(255, 0, 0, 0.4)'
    else if nowhp < 0.5 * maxhp
      repairColor = 'rgba(255, 65, 0, 0.4)'
    else if nowhp < 0.75 * maxhp
      repairColor = 'rgba(255, 255, 0, 0.4)'
    else
      repairColor = 'transparent'

我看代码里好像是没有边界值..? 25<50*0.5好像就直接去下一个分支了吧..没用过这个语言不知道对不对..

**Comment by KochiyaOcean** [comment]
（手动目瞪口呆
谁写的这个出来背锅吧（。

**Comment by jackarcher** [comment]
额..不太会用git..话说是不是要先watch才能发pull request啊..昨天晚上还想直接改了 但是不会弄Q.Q

**Comment by Ayaphis** [comment]
（手动目瞪口呆
竟然真的是代码错了。。。

**Comment by Ayaphis** [comment]
不是watch,不知道要不要fork，然后直接改了PR就行

**Comment by KochiyaOcean** [comment]
要 fork，不过写出这个 bug 的人不出来主动背锅吗
到底是谁呢（斜眼

**Comment by Ayaphis** [comment]
你PR错地方了=。=

**Comment by jackarcher** [comment]
好吧..我看已经被搞定了 本来一直当网盘用的..所以不太熟练...
