### ISSUE TITLE
多屏用户将窗口移到另一个屏幕，关闭多屏后不能显示窗口

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-ship-info#38]
Electron v0.34.3 x64
Win 10 Pro x64
Commit SHA: 9c4edd7bbd31a81f401d36c62fab8ec67c691118

Win 10 的任务栏有窗口，但是就是不能把窗口点出来。
其他需要新建窗口的插件没有此问题。

**Comment by yukixz** [comment]
用过多屏？

**Comment by Wafer-Li** [comment]
是的

**Comment by yukixz** [comment]
`window.shipInfoWindow.setPosition(0, 0)`

**Comment by yukixz** [comment]
ship info 会保存窗口坐标，多屏会保存到另一个屏幕上=。=

**Comment by yukixz** [comment]
@alvin-777 有什么好的解决方案么？

**Comment by Wafer-Li** [comment]
嗯，暂时解决了。
不过有必要找一个终极的解决办法。

**Comment by yukixz** [comment]
冲突了= =（

**Comment by Wafer-Li** [comment]
不过我倒想问一下，开发者工具都不见了之后，难道用 cmd 启动来输入命令吗？

**Comment by Ayaphis** [comment]
好像是取窗口位置的时候。。。取了两个.x=。=详见此commit

https://github.com/poooi/plugin-ship-info/commit/3b3a72103b4b98db8e9f8214d1874dd3025f418d

额，大概可以在任务右键Shift最大化？

**Comment by Wafer-Li** [comment]
不是很懂 js
不过可否参照一下 Akashic-records 的写法，
就是不记录插件的窗口坐标，插件的窗口坐标就是主程序的窗口坐标？
https://github.com/poooi/plugin-Akashic-records/blob/master/index.cjsx#L24-L25

**Comment by Ayaphis** [comment]
O O也是个解决方案

**Comment by yukixz** [comment]
= = 这个 alvin 有意改成保存坐标的形式的...

**Comment by alvin-777** [comment]
* 就是因为每次都移那个窗口太麻烦才改成让它记住未知的。。
* 2个x是我手滑了（复制粘贴呸）。。。因为Mac会自动把显示范围外的窗口移回来所以一直没发现。。。 >. <
* 这个貌似是Windows特有的问题（未验证）？我记得很久以前就有人提过如果把poi主窗口移到副显示屏，退出后拔掉屏幕再开poi。。。就再也找不到主窗口啦。。好像一直没有什么好的解决方案。。
* 临时解决方案：打开开发者工具，console输入`remote.getCurrentWindow().setPosition(0, 0)`
* 开发者工具可以用快捷键打开，Mac是`Cmd+Option+i`, Win 我记得好像是F12(?)

**Comment by Wafer-Li** [comment]
:joy: 我指的是……开发者工具也被移到副屏幕，然后就不见了。。。

**Comment by alvin-777** [comment]
开发者工具的位置貌似是chromium内核自己管理的。。我也不知道怎么办了。。。
![mdkd](https://cloud.githubusercontent.com/assets/13615512/11275556/e5c9390e-8f29-11e5-92a4-505e461639ff.jpg)

**Comment by KagamiChan** [comment]
2.0 版本应该能解决这个问题了
