### ISSUE TITLE
export info

### ISSUE THREAD

**Issue by ruiii** [poooi/plugin-ship-info#41]
<img width="299" alt="2015-11-20 17 13 21" src="https://cloud.githubusercontent.com/assets/11897118/11295986/2d1c4c44-8faa-11e5-909c-3fb342528742.png">

**Comment by dkwingsmt** [comment]
有点意思⋯⋯不过感觉如果不以图片格式导出的话工程量就超级大了

**Comment by taroxd** [comment]
不以图片导出的话工程量很小啊，把 state 里的东西全拉出来存成 CSON 就好了

**Comment by dkwingsmt** [comment]
恰恰相反……不以图片导出的话就意味着你要为舰娘信息做一个读取 cson 器

**Comment by Ayaphis** [comment]
为什么要做导入。。。
导出成CSV么
cson对非程序员不友好
图片的话我不了解相关API，目前已知的是electron只有窗口截图，没有页面截图

**Comment by dkwingsmt** [comment]
CSV 倒是不错，而且也不用做导入了……

**Comment by alvin-777** [comment]
我觉得csv可行

**Comment by ruiii** [comment]
虽然我觉得直接截图就可以了
多大点事（（

**Comment by Ayaphis** [comment]
too busy to implement this lead to now another problem ,
should i export ship names of the before or after translation?
i guess the names after translation are wanted.(won't provide choice
