### ISSUE TITLE
_ship[].api_slot[] 可能不存在于 _slotitems[] 中

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-ship-info#53]
![851334169_6846698799183868162](https://cloud.githubusercontent.com/assets/3337921/12069940/82330bae-b08f-11e5-9819-9b28d55e0c0f.jpg)
![851334343_9445660957167900833](https://cloud.githubusercontent.com/assets/3337921/12069941/83c9f64e-b08f-11e5-9746-0315914a8eb3.jpg)

虽然不知道为什么、但是出现了数据不一致（x

**Comment by taroxd** [comment]
![qq 20160101162847](https://cloud.githubusercontent.com/assets/6070540/12070286/c1b76b8e-b0a4-11e5-8460-064ce4ceab0c.jpg)

虽然不知道为什么 总之报错了
