### ISSUE TITLE
顯示鑑娘無裝備時的數值

### ISSUE THREAD

**Issue by eul721** [poooi/plugin-ship-info#58]
目前插件貌似沒有提共這個功能
![如圖](https://i.gyazo.com/880549337922ece0ce6339887c708338.png)

參考了KC3Kai的做法，
可以在中間這一大格裡加個"無裝數值/有裝數值"的選項
應該會很方便  不然想對照時還得拆裝

**Comment by KagamiChan** [comment]
done with a9d241b832d186ffbb3157be7026d2ac3cc40e6e
