### ISSUE TITLE
补强增设装备槽中的装备显示

### ISSUE THREAD

**Issue by FXuZ** [poooi/plugin-ship-info#59]
也不完全是bug, 只是觉得这个应该是可以改进的...
游戏中补强增设打的洞中的装备和主要的4格装备槽中的是分开的, 而且在poi的舰队面板中现在也有显示成分开的, 然而在舰娘信息插件中这两个是混在一起的所以如果像下面的截图中一样只有洞里有装备, 在插件里面就无法区分那个装备是在主槽中还是在洞里面了...
![screenshot taihou](http://ooo.0o0.ooo/2016/03/27/56f872df1042a.png)

**Comment by KagamiChan** [comment]
impl. via 3670fea38ae3ae5bec6a38a3783cf75060ab3c6a
