### ISSUE TITLE
改造完成和仍能改造是不是反过来了？

### ISSUE THREAD

**Issue by swordfeng** [poooi/plugin-ship-info#70]
现在poi能检查到的最新版本里改造完成和仍能改造好像反过来了。

**Comment by KagamiChan** [comment]
多谢指出，aab7dd65b0bb30e78b8c941bbebfc164964c7771 已经做了修正，虽然之后把描述和选项也换掉了
如果勾选检查 beta 版更新的话，下载到的 2.1.0-beta.x 应该已经没有问题了。2.1.0 的正式版计划这几天发布
