### ISSUE TITLE
等级排序时， 游戏内默认顺序为获取id 升序 插件默认顺序为获取id 降序

### ISSUE THREAD

**Issue by Evilcat325** [poooi/plugin-ship-info#71]
http://imgur.com/a/WW9Yy

给僵尸丸放了一个装备    游戏中lv 排序 是 最后获得的
插件排序 按照 获取id 降序  于是放到了第一个
应该是lv 降序 -》 sortno 升序 -》 获取id 升序 的节奏吧~

看改装顺序时候发现的- =   改装 他里面其实就是lv 的倒序 里面相当于获取id降序  
但是变成界面反过来的应该就是获取id 升序的节奏~     捞两只1级驱逐应该就可以测试

**Comment by Evilcat325** [comment]
啊 顺带舰种排序貌似也是 获取id 升序的节奏 
在nga 爬就贴看到的。。。

**Comment by Evilcat325** [comment]
看了代码感觉
```
if (a.id != b.id) return a.id - b.id
```
改成
```
if (a.id != b.id) return -(a.id - b.id)
```
就ok的节奏吧

**Comment by KagamiChan** [comment]
嗯，可以确认游戏里面的 lv，舰种和修理（HP）的排序都包含有按 api_id 的升序

我觉得需要考虑一下插件里面的其它排序是不是也要都带上对 api_id 的升序排序，这样一来也要加入更多的条件来让排序结果显得齐整。所以会一并做个修复，咕咕咕

**Comment by KagamiChan** [comment]
仔细想了一下，这里面还包括一个升序和降序的问题，游戏中是没有降序的，这些倒是可以一并解决……

**Comment by wafer-li** [comment]
😂 其实我一直有想查看谁更先结婚的需求

建议 98 级的可以按照剩余经验值排序

**Comment by KagamiChan** [comment]
@wafer-li 会实现和游戏内表现不一致的排序，我觉得可能直接给 98 级的船加个 popup 显示剩余经验值可能好一点，不过估计就是一个基本没有用户会发现的功能了……

**Comment by KagamiChan** [comment]
@wafer-li 把这个排序放到经验计算插件的舰娘列表下拉选单那里倒是可以……

**Comment by wafer-li** [comment]
@KagamiChan 第二个提议不错，那就不在这里整了。

**Comment by KagamiChan** [comment]
@wafer-li 经验计算新版本已发

**Comment by KagamiChan** [comment]
已修复
