### ISSUE TITLE
部分裸装数值显示不准确

### ISSUE THREAD

**Issue by zlyzly777** [poooi/plugin-ship-info#83]
插件版本 5.0.2，发现藤波改和矶风改的裸装数值不准确
![wsoubi](https://user-images.githubusercontent.com/36129742/35778057-8f7aab40-09f3-11e8-8327-875019082762.PNG)
没有任何装备的 Lv.76 藤波改回避，对潜，索敌分别是 79，57，45，选择为包含装备时和游戏中一致
![wosoubi](https://user-images.githubusercontent.com/36129742/35778083-f81fb8ac-09f3-11e8-9a86-5c1c505e95e6.PNG)
选择为裸装数值时，显示 82，59，50
同样，没有任何装备的 Lv.75 矶风改索敌为 39，选择为裸装数值时显示 31
变更装备，选择包含装备始终和游戏中一致，选择裸装数值始终显示不准确数值
尝试：开启或关闭头像，清空 poi 缓存，重装插件，禁用其他插件，问题依旧
手动安装 4.7.0 或 4.6.5，显示准确
手动安装 5.0.0 或更新至 5.0.2，显示不准确

**Comment by KagamiChan** [comment]
5.x 版本开始索敌对潜和回避开始使用是谁呼叫舰队数据库的数据进行计算，看来数据库有记录错误的地方，比如矶风改的数据库里面记录的初始索敌 为9，最大索敌为39。而 wikiwiki 中是 9 与 49。我有时间整理之后和大波胡提一下
