### ISSUE TITLE
针对18年冬活的出击计划beta最近会上线吗

### ISSUE THREAD

**Issue by HolicEro** [poooi/plugin-ship-info#84]
打算等这个出了以后再进场，如果最近没有计划的话就直接进场了

**Comment by KochiyaOcean** [comment]
和 17 秋是一个背景所以数据完全通用

**Comment by HolicEro** [comment]
@KochiyaOcean 用的8.1.0stable 所以出擊計畫插件裡沒有後段作戰的貼條信息，更新了8.2.0beta以後可以了，謝老闆
