### ISSUE TITLE
Deck Planner on English

### ISSUE THREAD

**Issue by Kvazikvark** [poooi/plugin-ship-info#89]
Good day. It would be very convenient if the names of the ships in Deck Planner were in English. In time of winter 2018 event they were translated. Thanks.

**Comment by KagamiChan** [comment]
sorry for that, I thought it was done
I'll look into it

**Comment by KagamiChan** [comment]
published a new version, seems to me all ship names get translated

I'll add ship avatars in planner sometime

**Comment by Kvazikvark** [comment]
thanks for operativeness
